### ISSUE TITLE
Release v0.1 of the plugin

### ISSUE THREAD

**Issue by astrofrog** [ejeschke/glue-ginga#12]
I'm finally getting back to this, and was thinking it would be great to have a first stable release of this plugin package.

@pllim @ejeschke - are we missing anything that should be included in a first release?

**Comment by pllim** [comment]
Do you want #10 in first before release? I think I am almost done with it but stuck at passing in WCS back to Glue data structure.

**Comment by astrofrog** [comment]
@pllim - yes, it'd be great if we could get that in before the release. Could you remind me what the WCS issue was?

**Comment by pllim** [comment]
@astrofrog , one of the wish list in #6 is to preserve header between data transfers. When I transfer data from Glue to Ginga, the header info is lost, so I cannot display the original header in Ginga's `Header` section. Is there a solution for this?

**Comment by astrofrog** [comment]
The header in glue is accessible at ``d.coords.header`` so I think you should be able to round-trip

**Comment by pllim** [comment]
Hmm. Has anyone tried this plugin under Qt5? I recently did a switch to Qt5. This plugin used to work in Qt4 but now in Qt5, when I click in "Put Data", it just popped up an empty Error dialog and I cannot close it.

```
$ conda list qt
# packages in environment at .../anaconda/envs/dadf:
#
pyqt                      5.6.0                    py35_0  
pyqtgraph                 0.9.11              np111py35_1    http://ssb.stsci.edu/astroconda
qt                        5.6.0                         1  
qtconsole                 4.2.1                    py35_1  
qtpy                      1.1.2                    py35_0  
```

**Comment by ejeschke** [comment]
Just tried with Qt5 on the Mac.  Seems ok.

**Comment by ejeschke** [comment]
Hold that.  Checking that conda is actually pulling in Qt5...

**Comment by pllim** [comment]
@ejeschke , no worries. I was using the version from my PR. Trying the plugin on `master`, that button worked. So the error must have been introduced in the PR somehow. Unfortunately, I don't have anymore time to work on the PR today. So, @astrofrog , go ahead and release the plugin as-is, we can put #10 in for the next release. Sorry for the trouble.

**Comment by ejeschke** [comment]
Just verified ok with qt5 on mac.

**Comment by astrofrog** [comment]
Everything is working fine for me with qt5

**Comment by astrofrog** [comment]
Done! https://pypi.python.org/pypi/glue-ginga/0.1

**Comment by ejeschke** [comment]
Thanks, @astrofrog !
