### ISSUE TITLE
AppVeyor privileges

### ISSUE THREAD

**Issue by astrofrog** [ejeschke/glue-ginga#13]
@ejeschke - would it be possible to add me to AppVeyor so I can control the builds if needed?

**Comment by ejeschke** [comment]
Sure.  Can you give me the quick instructions?

**Comment by astrofrog** [comment]
@ejeschke - sure, I think you need to go to

https://ci.appveyor.com/team

and add me as a user, then go to https://ci.appveyor.com/project/ejeschke/glue-ginga and Settings -> Permissions, then for User click on Inherit so it changes to Allow for the three first columns (I don't need the fourth).

**Comment by ejeschke** [comment]
The appveyor page for adding a user doesn't seem to use github ids.  It seems to want name, email address, role and password.  Am I missing something?

**Comment by astrofrog** [comment]
@ejeschke - hmm, that doesn't seem right. Don't worry about it for now, will see if I can figure it out later.

**Comment by astrofrog** [comment]
@ejeschke - in the team page, add a collaborator rather than a user and use thomas.robitaille@gmail.com as the email address. Thanks!

**Comment by ejeschke** [comment]
@astrofrog, I have added you as per instructions above.  Is this working as expected?

**Comment by astrofrog** [comment]
Yes, this works well now - thanks!
