### ISSUE TITLE
Integrate Glue plugin with DataImage

### ISSUE THREAD

**Issue by pllim** [ejeschke/glue-ginga#14]
Follow up to #6 and #10: Use `glue_ginga.qt.layer_artist.DataImage` (edited) in Glue plugin for Ginga.

[A quick attempt in #10](https://github.com/ejeschke/glue-ginga/pull/10#discussion_r92465329) resulted in `IndexError`. More investigation is needed.

**Comment by pllim** [comment]
`client` was removed in #20, so this is no longer possible.

**Comment by ejeschke** [comment]
@pllim, `DataImage` just got moved up a level to `glue_ginga.qt.layer_artist`, AFAIK.

**Comment by astrofrog** [comment]
@ejeschke is right, it's only the client code itself that has disappeared

**Comment by pllim** [comment]
Ah, okay. Thanks for the clarification!
