### ISSUE TITLE
Include in conda channel?

### ISSUE THREAD

**Issue by pllim** [ejeschke/glue-ginga#15]
While this is available under `pip`, I cannot find it in `conda-forge` nor AstroConda.

**Comment by ejeschke** [comment]
@pllim, is it someone at STScI maintaining the AstroConda channel?

**Comment by pllim** [comment]
@ejeschke , yes. We also accept contributions as PRs at https://github.com/astroconda/astroconda-contrib

**Comment by pllim** [comment]
@ejeschke , if you think AstroConda is appropriate for this and the package is ready (i.e., somewhat "stable"), then I can put it there.

**Comment by ejeschke** [comment]
What do you think, @pllim?

**Comment by pllim** [comment]
I think we can try releasing in AstroConda. However, it needs a GitHub release tag. I notice that there is no GitHub release, but @astrofrog did a release in PyPi. I am not sure how to reconcile this. Any idea?

**Comment by ejeschke** [comment]
Looks like the version is currently set at 0.1.  Shall I just make a git hub release "v0.1"?

**Comment by ejeschke** [comment]
Although if we want to push the exact same commits to PyPI the version probably ought to be bumped, and then make a github release and push it to PyPI.

**Comment by pllim** [comment]
IMHO, since you just fixed a bug, we can bump to 0.1.1 and have both PyPi and GitHub releases for that. I don't have PyPi account though.

**Comment by ejeschke** [comment]
Ok, so I made a 0.1.1 release on github.  Now I'll try to push it to PyPI.

**Comment by ejeschke** [comment]
@astrofrog, can you add me to the uploaders for `glue-ginga` on PyPI?  Or else push the current release up?

```bash
Submitting dist/glue-ginga-0.1.1.tar.gz to https://pypi.python.org/pypi
Upload failed (403): You are not allowed to edit 'glue-ginga' package information
error: Upload failed (403): You are not allowed to edit 'glue-ginga' package information
```

**Comment by astrofrog** [comment]
@ejeschke - I've added you as an owner on PyPI - can you try again?

**Comment by ejeschke** [comment]
@astrofrog, thank you--success.

**Comment by pllim** [comment]
This will be part of AstroConda after astroconda/astroconda-contrib#177 is merged. Is that sufficient or do we also want to include this somewhere else?

**Comment by pllim** [comment]
It is in AstroConda.
