### ISSUE TITLE
Travis CI failing

### ISSUE THREAD

**Issue by pllim** [ejeschke/glue-ginga#17]
See https://travis-ci.org/ejeschke/glue-ginga/builds/203503079

**Comment by ejeschke** [comment]
> >       result = view_shape(self.subset.data.shape, self.view)
> E       AttributeError: 'SubsetImage' object has no attribute 'subset'

Looks like something has changed in the base class on Glue side?

**Comment by pllim** [comment]
@astrofrog, any idea?

**Comment by ejeschke** [comment]
AppVeyor is failing with the same error message.

**Comment by astrofrog** [comment]
Seems like it's more likely due to a change on the ginga side - it looks like ``BaseImage.__init__`` now tries to access ``.shape`` which relies on ``.subset`` but the latter isn't defined until after ``BaseImage.__init__`` has been called.

**Comment by ejeschke** [comment]
> it looks like BaseImage.__init__ now tries to access .shape which relies on .subset but the latter isn't defined until after BaseImage.__init__ has been called.

Hmm, Ginga doesn't define or use a `subset` attribute.  But I see what you are saying--the `shape` property is overridden in the `SubsetImage`, and in that method it accesses instance variables that aren't yet defined. And the `BaseImage` constructor does access `shape` now.

I think this can be solved simply by moving the superclass constructor call after the attributes are defined.  Checking this now.

**Comment by ejeschke** [comment]
I think commit 51ed55cb98a6f6c0527cdba2a754427125cac719 fixes this.

**Comment by ejeschke** [comment]
Looks like the travis and appveyor builds are passing.

**Comment by pllim** [comment]
Once https://travis-ci.org/ejeschke/glue-ginga/builds/204261616 passed, we can close this. Thanks, @ejeschke !

**Comment by ejeschke** [comment]
The build seems to be stalled, or taking a really long time to complete.

**Comment by pllim** [comment]
I think that happens with Travis CI sometimes. We'll just have to wait it out.

**Comment by pllim** [comment]
Passed!
