### ISSUE TITLE
No data viewers selectable from Glue when using Glue plugin for Ginga

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/glue-ginga#18]
When I start a Glue session from the Glue plugin for Ginga, I can drag a file into the window and it appears in the data manager.  But when I drag the file to the glue main workspace, the dialog won't let me select any viewer of any kind, including the native 2D viewer.  The dialog looks like this:

![data_viewer_dialog](https://cloud.githubusercontent.com/assets/1305473/23288885/376e524a-f9ea-11e6-8529-a5d8a240df73.png)

**Comment by ejeschke** [comment]
ping @pllim

**Comment by ejeschke** [comment]
@astrofrog, I'm diving in, but any pointers on where to look?  Do I need to now do some registration of viewers as part of starting a glue session?  I think I followed the recipe in `qglue`, IIRC.

This was working with an earlier version of the plugin and respective viewers.

**Comment by astrofrog** [comment]
@ejeschke - yes, try starting glue with ``glue -v`` and look for errors when loading plugins

**Comment by astrofrog** [comment]
Ah wait you are still starting glue from ginga when the problem occurs?

**Comment by pllim** [comment]
I just tested this, on Windows no less, and everything worked. Is this really a Glue problem of not able to decipher what file type it is?

**Comment by ejeschke** [comment]
@pllim, do you see this issue when running the Glue plugin in Ginga after the recent changes?

**Comment by pllim** [comment]
@ejeschke , I have never encountered this problem and could not reproduce it back in https://github.com/ejeschke/glue-ginga/issues/18#issuecomment-282318868 . If you still have the data file that caused the problem, could you please share?

**Comment by ejeschke** [comment]
I can't reproduce it now.  I think I will close the issue and will reopen it later if it comes up again.
