### ISSUE TITLE
Fix compatibility with glue-core v0.11.dev

### ISSUE THREAD

**Issue by astrofrog** [ejeschke/glue-ginga#19]
The developer version of glue has completely re-written viewers (including the image viewer), so I need to update this plugin to work correctly with the latest version. This issue is to serve as a heads-up that I am aware things are broken, and also that I'll work on it :)

**Comment by pllim** [comment]
Thanks for the heads up! In the meantime, should we pin versions on `setup.py`?

**Comment by astrofrog** [comment]
I'll fix this before glue-core v0.11 is released, so I don't think pinning is needed at this point.
