### ISSUE TITLE
Glue plugin in Ginga broken with Glue 0.11

### ISSUE THREAD

**Issue by pllim** [ejeschke/glue-ginga#22]
I am using dev version of Ginga, Glue 0.11 from `pip`, and dev verson of `glue_ginga`. When I  press "Start Glue" in the plugin, I get:
```
Error making callback 'activated': __init__() got an unexpected keyword argument 'maximized'
Traceback:
  File ".../ginga/misc/Callback.py", line 128, in make_callback
    res = method(*cb_args, **cb_kwdargs)

  File ".../glue_ginga/plugins/Glue.py", line 164, in <lambda>
    b.start_glue.add_callback('activated', lambda w: self.start_glue_cb())

  File ".../glue_ginga/plugins/Glue.py", line 305, in start_glue_cb
    self.glue_app = qglue()

  File ".../glue_ginga/plugins/Glue.py", line 378, in qglue
    ga = GlueApplication(data_collection=dc, maximized=False)
```

I have a vague recollection of adding the `maximized` keyword myself and this used to work, though I have not used it in a while.

c/c @astrofrog 

xref https://github.com/ejeschke/glue-ginga/pull/20#issuecomment-324969576

**Comment by pllim** [comment]
I traced this to glue-viz/glue#694

**Comment by astrofrog** [comment]
Good catch! The ``maximized`` argument is now passed to ``start`` not ``GlueApplication``

**Comment by pllim** [comment]
So, what's the fix for this? It's not obvious to me.

**Comment by astrofrog** [comment]
In the following code ``show`` should be changed to ``start`` and the ``maximized`` keyword can be passed to ``start``:

https://github.com/ejeschke/glue-ginga/blob/master/glue_ginga/plugins/Glue.py#L313

and removed here:

https://github.com/ejeschke/glue-ginga/blob/master/glue_ginga/plugins/Glue.py#L378

**Comment by pllim** [comment]
@astrofrog , I assume this change will not be backward compatible, but does it matter here?

**Comment by astrofrog** [comment]
@pllim - no, the plugin is already no longer compatible with glue-core <= 0.11

**Comment by ejeschke** [comment]
> In the following code `show` should be changed to `start` and the maximized keyword can be passed to start

We can't change show() to start() because this causes glue to grab the GUI thread and not release it.  We'll have to figure out a different way to pass the maximize=False.

**Comment by pllim** [comment]
Thanks, @ejeschke ! I think just moving the `show()` one line up fixed the problem.

However, when Glue is started from Ginga using that plugin, I can no longer access IPython console within Glue (no problem with that if Glue is not started from that Ginga plugin):
```python
  File ".../glue/app/qt/application.py", line 891, in _toggle_terminal
    if self._terminal.isVisible():
AttributeError: 'NoneType' object has no attribute 'isVisible'
```

**Comment by ejeschke** [comment]
It's possible that there is something being bypassed in the glue initialization the way we are launching it, or that something has changed with the new glue that we need to call to set things up to enable the terminal.  This would be my guess (based on your traceback) without having looked into the new glue changes yet.

**Comment by astrofrog** [comment]
You need to start up glue with ``start`` not ``show`` in order to get the IPython terminal

**Comment by pllim** [comment]
What a dilemma. Ginga won't work properly if I use start but I lose Glue IPython terminal if I don't...

**Comment by astrofrog** [comment]
I'll take a look more closely and see if this can be resolve in glue or glue-ginga

**Comment by pllim** [comment]
Thanks!

**Comment by ejeschke** [comment]
It would be good if we could resolve that before bumping the release, but I'd recommend at least just merging the fix for the 'maximize' problem.  The plugin is still quite useful even without the IPython terminal.

**Comment by astrofrog** [comment]
If you merge the maximize fix I can fix the terminal in a separate PR
