### ISSUE TITLE
v0.1.1 install_requires list not compatible with latest astroconda recipe

### ISSUE THREAD

**Issue by rendinam** [ejeschke/glue-ginga#28]
The `install_requires` dependencies found in `setup.py` of the v0.1.1 release are not compatible with the latest introduction of `glue-core`. This prevents building the conda package for that version using the recipe found in https://github.com/astroconda/astroconda-contrib

The `install_requires` list in`setup.py` as found in master corrects this issue.

**Comment by astrofrog** [comment]
@rendinam - I just released v0.2, does that help?

**Comment by rendinam** [comment]
Indeed it does. Thanks!

**Comment by ejeschke** [comment]
@astrofrog, @pllim, we should probably add some release notes to 0.2.  Maybe the main item is just compatibility with updates to glue.

**Comment by pllim** [comment]
I haven't been working on this much lately, so I have no notes to add. :sweat_smile:

**Comment by astrofrog** [comment]
I did add some notes to the 0.2 section here: https://github.com/ejeschke/glue-ginga/blob/master/CHANGES.rst#02-2017-11-03 - do you mean somewhere else?

**Comment by pllim** [comment]
@astrofrog at https://github.com/ejeschke/glue-ginga/releases
