### ISSUE TITLE
Improve Glue global plugin for Ginga

### ISSUE THREAD

**Issue by pllim** [ejeschke/glue-ginga#6]
This is a follow-up to #5.

These are addressed in #10:
- [x] Start Glue in a non-maximized mode (currently hardcoded values are no good for small screen on a laptop).
- [x] Add instructions.
- [x] Make it clear that "Get Data" loads Glue data into the currently active Ginga channel.
- [x] Make it clear that "Put Data" sends the currently active buffer to Glue.
- [x] Enable/disable buttons in a way that is intuitive to users.
- [x] Should we allow plugin to start *multiple* Glue sessions? (No.) If so, how do we make it stop or send/get data to/from the selected session? (N/A)
- [x] How to handle use case when user terminates Glue outside of this plugin? Note: Add Qt callback for close/quit on q-application. This needs also glue-viz/glue#1168 to be merged and released first.
- [x] Transfer WCS and header from Glue image to/from Ginga.
- [x] How to get/put table data properly?
- [x] How to handle "Close" and "Stop Glue" behavior in an intuitive way?

**Comment by pllim** [comment]
Also, I just found out that "Stop Glue" and "Close" basically do the same thing. I find it confusing when there are duplicate GUI elements, so I am going to remove the "Stop Glue" button.

**Comment by ejeschke** [comment]
Well, `Close` closes the plugin, which specifically calls the stops function on its way to closing everything.  So they are not exactly equivalent (one is stop and one is stop + close).  I would expect that the user might want to be able to close the glue session without closing the plugin. Maybe it would be better to just remove the `stop_glue()` call from `close()`, because it might also be the case that the user wants to close the plugin but keep running the session.

**Comment by pllim** [comment]
@ejeschke , in my work for this PR, I realized that WCS objects in Ginga's `wcsmod.py` can only read from header. So to transfer WCS from Glue to Ginga, I have to convert the WCS to FITS header, and then back. While I understand that `wcsmod.py` needs to be compatible with many different WCS packages, such conversion is not very efficient. For now, it works but I welcome any ideas for improvement.

**Comment by pllim** [comment]
@astrofrog , I can't figure out a way to convert WCS from Ginga's `AstroImage` to Glue data even with the Jupyter notebook you provided in our post-workshop meeting. I need to pass in the Numpy array and the associated WCS, and somehow link them together.

**Comment by pllim** [comment]
I thought this would work because I see that MOSViz does a similar thing in its loader but I keep getting "Data object has no rfind" error.

``` python
        ...
        data_np = image.get_data()
        name = image.get('name', 'noname')
        kwargs = {'label': name, name: data_np}

        try:
            gdata = Data(**kwargs)

            # Pass in WCS for image.
            if isinstance(image, AstroImage.AstroImage):
                gdata.coords = coordinates_from_wcs(image.wcs.wcs)

            self.glue_app.add_data(gdata)
            ....
```

**Comment by ejeschke** [comment]
> I realized that WCS objects in Ginga's wcsmod.py can only read from header. So to transfer WCS from Glue to Ginga, I have to convert the WCS to FITS header, and then back. 

I think if you already have a valid astropy WCS, you should be able to make a the WCS for Ginga by simply sharing the already existing WCS.  Something like:

``` python
    image = AstroImage(glue_data_np, logger=self.fv.logger)
    image.wcs = wcsmod.AstropyWCS(self.fv.logger)
    image.wcs.wcs = glue_wcs
```

should work.  Of course it would be nice to transfer over the header as well.

But I want to reemphasize that I think we really want to use what has already been prepared for the ginga viewer in glue.  We should be able to write:

``` python
    from glue_ginga.qt.client import DataImage
    image = DataImage(glue_data_obj, component, view)
```

See [this](https://github.com/ejeschke/glue-ginga/blob/master/glue_ginga/qt/client.py)

**Comment by ejeschke** [comment]
We may need to make sure that object has the header as well.

**Comment by astrofrog** [comment]
@pllim - this is not well documented but you can do:

```
In [5]: from glue.core import Data

In [6]: from glue.core.coordinates import WCSCoordinates

In [18]: d = Data(values=array, label='mydata')

In [19]: d.coords = WCSCoordinates(wcs.to_header())
```

The conversion of WCS back to a header (and then internally back to a WCS) is silly and we should make it so that the header doesn't have to be specified, and the WCS should be enough. I've opened an issue here: https://github.com/glue-viz/glue/issues/1170 (PRs welcome!)

**Comment by pllim** [comment]
Re: `WCSCoordinates` in Glue -- see glue-viz/glue#1171

**Comment by pllim** [comment]
@ejeschke , ah yes, I forgot about `client.py`. I'll investigate that next. First, I want to get the plugin works independently first just to understand the interface if nothing else.

Regarding usage of `wcsmod.AstropyWCS(...)`, wouldn't that bypass Ginga's user setting for the preferred WCS package? Is that desirable? I know that in plugins like `MultiDim` and `SaveImage`, we already bypass the preferred FITS package setting but we have not yet done such things for WCS.

**Comment by pllim** [comment]
> We may need to make sure that object has the header as well.

@ejeschke , currently, I cannot find a way to read header info from Glue data object (see glue-viz/glue#1172). So, I am not sure what is the best way to go about this yet.

**Comment by pllim** [comment]
@astrofrog , in your example above, what is the next step? That is, how do you pass `d` into `qglue` app? Passing it in with `add_data(d)` still gives me the same error. But now I figured out how to get the entire traceback:

``` python
Traceback (most recent call last):
  File ".../glueviz-0.10.0.dev3176-py3.5.egg/glue/core/application_base.py", line 25, in wrapper
    return func(*args, **kwargs)
  File ".../glueviz-0.10.0.dev3176-py3.5.egg/glue/core/application_base.py", line 179, in add_data
    datasets.append(load_data(path))
  File ".../glueviz-0.10.0.dev3176-py3.5.egg/glue/core/data_factories/helpers.py", line 235, in load_data
    lbl = data_label(path)
  File ".../glueviz-0.10.0.dev3176-py3.5.egg/glue/core/data_factories/helpers.py", line 257, in data_label
    _, fname = os.path.split(path)
  File ".../lib/python3.5/posixpath.py", line 103, in split
    i = p.rfind(sep) + 1
AttributeError: 'Data' object has no attribute 'rfind'
```

**Comment by ejeschke** [comment]
> Regarding usage of wcsmod.AstropyWCS(...), wouldn't that bypass Ginga's user setting for the preferred WCS package? Is that desirable?

Well in this case the user opened the file in glue and you are viewing it in ginga.  I'm not sure, but I would guess glue always uses `astropy.wcs`, so if you are going to share it you need to create a `AstropyWCS` wrapper for ginga.  It might be a possibly useful option to be able to reconstruct the wcs from the header, if that can be retrieved from glue.  Maybe that could be a plugin setting in a future enhancement.

**Comment by pllim** [comment]
>  It might be a possibly useful option to be able to reconstruct the wcs from the header, if that can be retrieved from glue.

That is what it is basically doing now: Glue WCS (Astropy) -> header -> Ginga WCS (based on user setting)

**Comment by ejeschke** [comment]
> That is what it is basically doing now: Glue WCS (Astropy) -> header -> Ginga WCS (based on user setting)

In that case you could just import `ginga.wcsmod.WCS` (which is assigned to the user's choice of wcs package) and build the wcs object with that.  But if you are just making a straight `AstroImage` and use `set_keywords()` to update the header it will rebuild the wcs using the user's preference.
