### ISSUE TITLE
Add RGB feature

### ISSUE THREAD

**Issue by ejeschke** [ejeschke/glue-ginga#8]
The Ginga viewer for Glue is missing the "RGB" feature to load 3 different mono images from a data set into an RGB image.

This should be straightforward to add, as Ginga supports RGB images.

**Comment by ejeschke** [comment]
@astrofrog and @pllim, I've updated the package (during my long flight back) to fix the PVSlicer tool and Spectrum tool, as well as other minor fixes and polish.  When you have a moment, take a quick look and report issues for any other obvious things that are not working compared to the matplotlib-based viewer.  

For testing, you will need to update your ginga installation as I added support for Glue's XRange and YRange ROIs.  The plugin does force this on installation if you haven't already.

**Comment by pllim** [comment]
I never use the RGB feature. But maybe @stscieisenhamer or @nmearl have?

**Comment by pllim** [comment]
I wonder if we can take advantage of astropy/astropy#5535, which will be available under Astropy 1.3.
